### ISSUE TITLE
Offset is not respected when linking to a hash from another page

### ISSUE THREAD

**Issue by jaydenseric** [flesler/jquery.localScroll#24]
With localScroll version 1.3.5 and Chrome 37 the `offset` option is not respected when linking to a hash from another page.

It seems to work in Firefox 37 and Safari 6.1.2.

**Comment by sitoagency** [comment]
@jaydenseric If you mean clicking a link on pageA to pageB#someid, it never worked for me and i've been using jQuery scrollTo from years. I've solved the issue with this snippet:

```	
        var localOffset;
	var hashOffset;
	var finalOffset;
	
	localOffset = jQuery('.site-header').outerHeight();

        function offsetAnchor() {
		if(location.hash.length !== 0) {
			hashOffset = jQuery(location.hash).offset().top;
			finalOffset = hashOffset - localOffset;
			window.scrollTo(window.scrollX, finalOffset);
		}
	}
	window.setTimeout(offsetAnchor, 250);
```

edit: just noticed the post is from 2014 💯
