### ISSUE TITLE
Introduce a sample in README.md

### ISSUE THREAD

**Issue by bhagyas** [flesler/jquery.localScroll#27]

**Comment by flesler** [comment]
Not sure I understand what you mean, could you elaborate?
Thanks

**Comment by bhagyas** [comment]
Add a basic code block demonstrating a sample use case.

**Comment by flesler** [comment]
The Github project page has a readme showing how to install it, there's also a demo showing the plugin in action.

**Comment by flesler** [comment]
I see what you mean though, I'll try to add sample code block
