### ISSUE TITLE
NPM dependencies

### ISSUE THREAD

**Issue by coreyworrell** [flesler/jquery.localScroll#28]
If I understand correctly, localScroll sets a dependency for scrollTo in it's package.json, but doesn't actually include it. So you have `npm install jquery.scrollto` yourself and then include it, (or `require('jquery.localscroll/node_modules/jquery.scrollto/jquery.scrollTo')`.

localScroll should `require('jquery.scrollto')` correct?

**Comment by flesler** [comment]
Technically yes, though it doesn't use it directly (what the require() returns) but rather assumes it's present on the jQuery prototype.
In that past I added scrollTo as a dependency (on AMD though) and a load of complaints started coming.

What you report seems correct but I'm not sure of the consequences of making that change on existing setups, I'll leave this opened and we'll see if there's more input or +1's with some time.

You surely know that the fix (on your side ofc) is to `require('jquery.scrollto')` somewhere in the code.
