### ISSUE TITLE
I want to convert all link instead 2 ID

### ISSUE THREAD

**Issue by Ataurr** [flesler/jquery.localScroll#30]
Hello 
Thanks for this awesome scroll plugin.

I am try to use  `$.localScroll(...)` but instead 2 ID like #accordian #testimonial.  but no luck

i have tried filter this is also not working for me. maybe i am doing wrong something ?

can you please provide me details how i can use without 2 ID.

Thanks very much for help

**Comment by flesler** [comment]
Hi,

Try this:
```js
$(document).ready(function() {
  $.localScroll();
});
```

For user support you should rather ask on sites like StackOverflow where many more people are actively respondind.
