### ISSUE TITLE
does not work $target.is(":animated") and $target.stop(true)

### ISSUE THREAD

**Issue by VeX78rus** [flesler/jquery.localScroll#39]
in the old version I saw an additional event "._scrollable()". Together with the old version jquery.ScrollTo.1.4.6 it work. I want to use the latest version, but my knowledge is not enough to fix this.

**Comment by VeX78rus** [comment]
sorry jquery.localScroll**To**.1.4.6

**Comment by VeX78rus** [comment]
i am stupid jquery.ScrollTo.1.4.6

**Comment by VeX78rus** [comment]
there is someone alive here?

**Comment by VeX78rus** [comment]
???

**Comment by flesler** [comment]
Hi, this is not the best place to ask for help. It's rather for reporting issues.
You should ask for help on sites like stackoverflow instead

**Comment by VeX78rus** [comment]
Do not you think this is problem? you write that it works but in fact it does not work

**Comment by VeX78rus** [comment]
although the old version works correctly

**Comment by VeX78rus** [comment]
more precisely, this does not work when target: 'body' but if target: window its work

**Comment by VeX78rus** [comment]
maybe there is something missing here $target....().is(":animated")

**Comment by flesler** [comment]
I don't understand exactly what the issue is. Please provide a demo HTML+JS that shows the issue, explaining what it should do and what happens instead. Thanks

**Comment by VeX78rus** [comment]
you write:

31 target: window, // What to scroll (selector or element). The whole window by default.

I use the animation of a selector " target: 'body' " and its not work:

86 if (settings.stop) {
87 $target.stop(true); // remove all its animations
88 }

all time $target.stop(true) = false
animation creates a long queue when pressed several times
it seems to me I expressed myself quite clearly?

**Comment by VeX78rus** [comment]
if "target: window" its work

**Comment by VeX78rus** [comment]
you can check it here
http://kirichik.com/rhythm/index-15.html

**Comment by VeX78rus** [comment]
there is used the old version of the plug-in, but the replacement for a new one does not solve the problem.
and there are very old versions of the plugins used and, oddly enough, it works!
http://www.hdf.la

**Comment by VeX78rus** [comment]
I'm no expert, and I can't fix it, though, perhaps the problem has a simple solution

**Comment by VeX78rus** [comment]
I fixed it this way, but I do not know if it's right
$(this).stop(true)

**Comment by flesler** [comment]
The `target` needs to be `window`, not `'body'`. Sorry I cannot go through your codebase debugging issues.
If you can reproduce the issue using localScroll's demo site and verify it's a bug in the plugin, I'll check that out.

**Comment by VeX78rus** [comment]
ok I realized that if the body is a window, it works $target.stop(true)
But it does not work as before $target.is(":animated") even if target: window

**Comment by VeX78rus** [comment]
forgive me for my English

**Comment by VeX78rus** [comment]
sorry. demo on your site works correctly. possible conflict with other js code. or the event handler is installed somehow differently. my knowledge is not enough to understand this. I can only say that on very old versions of your plug-ins it worked. if you are not hard could you explain why.

**Comment by VeX78rus** [comment]
Perhaps the code I use was written with old versions of the plugins, but after updating stopped working as expected.

**Comment by flesler** [comment]
Maybe related to #38
