### ISSUE TITLE
ITS NOT WORK: $target.is(':animated') AND  $target.stop(true)

### ISSUE THREAD

**Issue by VeX78rus** [flesler/jquery.localScroll#40]
its worked "$target.stop(true)" if only "target: window" or if the change on "$(this).stop(true)".
what to do with it I did not understand "$target.is(':animated')"

**Comment by flesler** [comment]
Please don't create more issues when you already reported in #39. Let's continue the conversation there

**Comment by VeX78rus** [comment]
you write:

31     target: window, // What to scroll (selector or element). The whole window by default.

I use the animation of a selector " target: 'body' " and its not work:

86     if (settings.stop) {
87         $target.stop(true); // remove all its animations
88     }

all time $target.stop(true) = false
animation creates a long queue when pressed several times
it seems to me I expressed myself quite clearly?
